  infoset:
    command: python docker/api.py
    env_file: ./infoset/env/api.env
    build: .
    ports:
      - "8000:8000"
    links:
      - redis
      - celery
      - mysql
    hostname: localhost
    
  celery:
    build: .
    env_file: ./infoset/env/api.env   
    command: celery worker -A infoset.api.post.celery --loglevel=debug
    links:
      - redis

  redis:
    hostname: localhost
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    build: ./docker/mysql/
    env_file: ./infoset/env/api.env
    volumes:
      - ./data/infoset:/var/lib/mysql
    ports:
      - "3306:3306"